### PR TITLE
Upgrade from Python 2.x to 3.7

### LINKED ISSUE #7: Migrate to Python 3.7
We are going to drop support for Python 2.7 and migrate everything to Python 3.7.

### PR DESCRIPTION
**Pull request by neomatrix369**
Converted all .py files from python 2.x to 3.7. Also added instructions in the README

Fixes #7 

Merging of this PR is dependent on merging of https://github.com/julianghionoiu/tdl-client-python/pull/19 and updating the tdl-client-python package version number in the requirements.txt file

### CODE REVIEW

**Comment by neomatrix369** [comment]
@julianghionoiu This PR is ready to be reviewed

**Comment by julianghionoiu** [comment]
Have you managed to successfully test this in a completely new virtualenv?

I get the following error when running:
```
Traceback (most recent call last):
  File "/Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/lib/send_command_to_server.py", line 3, in <module>
    from tdl.runner.challenge_session import ChallengeSession
  File "/Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/venv/lib/python3.7/site-packages/tdl/runner/challenge_session.py", line 1, in <module>
    from tdl.runner.challenge_server_client import ChallengeServerClient, ClientErrorException, OtherCommunicationException, \
  File "/Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/venv/lib/python3.7/site-packages/tdl/runner/challenge_server_client.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

This hint towards some missing dependencies in setup.cfg.

**Comment by julianghionoiu** [comment]
I have added "requests" to the setup.cfg but now I am getting a runner specific error:
```
/Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/venv/bin/python /Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/lib/send_command_to_server.py
Traceback (most recent call last):
  File "/Users/julianghionoiu/Documents/Work/Projects/tdl/tdl-runners/tdl-runner-python/lib/send_command_to_server.py", line 4, in <module>
    from .solutions.SUM import sum_solution
ModuleNotFoundError: No module named '__main__.solutions'; '__main__' is not a package

Process finished with exit code 1
```

**Comment by neomatrix369** [comment]
@julianghionoiu I don't get the exact same errors, its also because Im on Conda but it shouldn't differ.

We shouldn't have missed the version numbers in the `setup.py`, I had put a note for us. Can we do something to avoid this in the future.

This reminds me to do a couple of things to prevent this from happening in the future. I think we have discussed this offline, I'll let you know when I fix them.

**Comment by neomatrix369** [comment]
Ran the `tdl-runner-python`:

```
Connecting to run.befaster.io

Your progress (0/2):
 > SUM (1 round)  -   warmup - Add two numbers
      └── SUM_R1  - not started
 . HLO (2 rounds) - official - Hello World !
      ├── HLO_R1  - not started
      └── HLO_R2  - not started
---------------------

Type "start" and press enter to start the selected challenge.
```

**Comment by neomatrix369** [comment]
I found issues when doing the challenge, so will debug and let you know. Will have to test the older version at the same time.

**Comment by neomatrix369** [comment]
I didn't get the above message anymore, not sure what happened, I'm thinking switching tot he Python 3 environment resolved it.

**Comment by neomatrix369** [comment]
Very strange as it should have thrown some other python related compilation error.

**Comment by neomatrix369** [comment]
```
PYTHONPATH=lib python lib/send_command_to_server.py
Connecting to run.befaster.io

Your progress (2/2):
 ✓ SUM (1 round)  -   warmup - completed in 19 min (+0 min penalty)
 ✓    └── SUM_R1  - completed in 19 min (+0 min penalty)
 ✓ HLO (2 rounds) - official - completed in 2 min (+0 min penalty)
 ✓    ├── HLO_R1  - completed in 1 min (+0 min penalty)
 ✓    └── HLO_R2  - completed in 1 min (+0 min penalty)
---------------------

Nicely done! All challenges have been completed. No actions available.
Now, wait for the upload to finish and that's it. You can relax now!
```

**Pull request merged**
